version: '3'

networks:
  nw_wapp_links_manager:

services:
  nginx:
    restart: always
    container_name: wapp_links_manager_nginx
    hostname: nginx_local
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php_fpm
    networks:
      - nw_wapp_links_manager

  php_fpm:
    restart: always
    container_name: wapp_links_manager_php_fpm
    hostname: php_fpm
    build:
      context: ./docker/php-workspace
      dockerfile: ./Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/php-workspace/logs/log1:/var/log/
      - ./docker/php-workspace/logs/log2:/usr/local/var/log
    networks:
      - nw_wapp_links_manager

  cron:
    restart: always
    container_name: wapp_links_manager_cron
    hostname: cron
    build:
      context: ./docker/cron
      dockerfile: ./Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/cron/crontab:/etc/crontab
    networks:
      - nw_wapp_links_manager